using System;
using System.Text;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;



namespace ElectricityBillProject.Models
{
    public class TinyPdf
    {
        public static byte[] MakeSimpleReceipt(string title, string[] lines)
        {
            MemoryStream ms = new MemoryStream();
            var wr = new BinaryWriter(ms);
            void W(string s){ wr.Write(Encoding.ASCII.GetBytes(s)); }

            W("%PDF-1.4\n");

            string content = "BT /F1 14 Tf 200 800 Td (JBVNL – Jharkhand Bijli Vitran Nigam Limited) Tj ET\n";
            content += "BT /F1 12 Tf 200 780 Td (Customer Care: support@jbvnl.com) Tj ET\n";

            int y = 740;
            foreach (var line in lines)
            {
                content += "BT /F1 12 Tf 60 " + y + " Td (" + Escape(line) + ") Tj ET\n";
                y -= 20;
            }
            content += "BT /F1 10 Tf 200 60 Td (Generated by JBVNL Utility Suite) Tj ET\n";

            byte[] cbytes = Encoding.ASCII.GetBytes(content);
            int len = cbytes.Length;

            string fontObj = "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n";
            string contObj = "5 0 obj << /Length " + len + " >> stream\n" + content + "endstream endobj\n";
            string pageObj = "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 5 0 R /Resources << /Font << /F1 4 0 R >> >> >> endobj\n";
            string pagesObj = "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n";
            string catObj = "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n";

            long o1,o2,o3,o4,o5;
            W(catObj); o1=ms.Position;
            W(pagesObj); o2=ms.Position;
            W(pageObj); o3=ms.Position;
            W(fontObj); o4=ms.Position;
            W(contObj); o5=ms.Position;

            long xrefStart = ms.Position;
            W("xref\n0 6\n");
            W("0000000000 65535 f \n");
            W(Pad(o1) + " 00000 n \n");
            W(Pad(o2) + " 00000 n \n");
            W(Pad(o3) + " 00000 n \n");
            W(Pad(o4) + " 00000 n \n");
            W(Pad(o5) + " 00000 n \n");
            W("trailer << /Size 6 /Root 1 0 R >>\nstartxref\n");
            W(xrefStart.ToString() + "\n%%EOF");

            return ms.ToArray();
        }

        static string Pad(long v)
        {
            string s = v.ToString();
            while (s.Length < 10) s = "0" + s;
            return s;
        }
        static string Escape(string s)
        {
            if (s == null) return "";
            return s.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)").Replace("\r"," ").Replace("\n"," ");
        }
    }
}
